name: render
variables:
  - name: base_url
    value: https://and-2yw6.onrender.com/
  - name: token_admin
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGVyZmlsIjoiQURNSU4iLCJzdWN1cnNhbF9pZCI6MSwiY2xpZW50ZV9pZCI6bnVsbCwidGlwb19jbGllbnRlIjpudWxsLCJhcHAiOiJpbnRlcm5vIiwiaWF0IjoxNzg5NjY2NDI2LCJleHAiOjE3ODk2OTUyMjZ9._4u8oYACLwrjFuTXxD9asOEy_LG4p7zyJiKvTT6tJ5k
  - name: token_tienda
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicGVyZmlsIjoiQ0xJRU5URSIsInN1Y3Vyc2FsX2lkIjpudWxsLCJjbGllbnRlX2lkIjoxLCJ0aXBvX2NsaWVudGUiOiJNSU5PUklTVEEiLCJhcHAiOiJ0aWVuZGEiLCJpYXQiOjE3ODk2NjI4NTcsImV4cCI6MTc5MjI1NDg1N30.p4t05_XH6VzkAZkzOymXugtHatl3U4wuy7zjWOp4yR4
  - name: token_mayorista
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwicGVyZmlsIjoiQ0xJRU5URSIsInN1Y3Vyc2FsX2lkIjpudWxsLCJjbGllbnRlX2lkIjoyLCJ0aXBvX2NsaWVudGUiOiJNQVlPUklTVEEiLCJhcHAiOiJ0aWVuZGEiLCJpYXQiOjE3ODk2NjQ2MjIsImV4cCI6MTc5MjI1NjYyMn0.pC2ft3SQP7x25-MMkxq1FYDB4UloLDlI2nrjsxMr5YM
  - secret: true
    name: stripe_secret_key
